server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reporting
    username: reporting_user
    password: reporting_pass
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    topic: workorders.events